In [262]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/2023-ml-midterm-p4/submit_sample.csv
/kaggle/input/2023-ml-midterm-p4/test_data/test_2021.csv
/kaggle/input/2023-ml-midterm-p4/test_data/test_2022.csv
/kaggle/input/2023-ml-midterm-p4/train_data/train_2019.csv
/kaggle/input/2023-ml-midterm-p4/train_data/train_2016.csv
/kaggle/input/2023-ml-midterm-p4/train_data/train_2020.csv
/kaggle/input/2023-ml-midterm-p4/train_data/train_2017.csv
/kaggle/input/2023-ml-midterm-p4/train_data/train_2015.csv
/kaggle/input/2023-ml-midterm-p4/train_data/train_2018.csv

In [263]:
import random
import os
seed = 42
random.seed(seed)
np.random.seed(seed)
os.environ["PYTHONHASHSEED"] = str(seed)

In [264]:
df = dict()
df['2015'] = pd.read_csv('/kaggle/input/-')
df['2016'] = pd.read_csv('/kaggle/input/-')
df['2017'] = pd.read_csv('/kaggle/input/-')
df['2018'] = pd.read_csv('/kaggle/input/-')
df['2019'] = pd.read_csv('/kaggle/input/-')
df['2020'] = pd.read_csv('/kaggle/input/-')

tf = dict()
tf['2021'] = pd.read_csv('/kaggle/input/-')
tf['2022'] = pd.read_csv('/kaggle/input/-')

submit = pd.read_csv('/kaggle/input/-')
print(df['2015'].info())
print(df['2016'].info())
print(df['2017'].info())
print(df['2018'].info())
print(df['2019'].info())
print(df['2020'].info())

print(submit.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Country                       158 non-null    object
 1   Region                        158 non-null    object
 2   Happiness Rank                158 non-null    int64
 3   year                          158 non-null    int64
 4   Standard Error                158 non-null    float64
 5   GDP per capita                158 non-null    float64
 6   Social support                158 non-null    float64
 7   Healthy Life Expectancy       158 non-null    float64
 8   Freedom to make life choices  158 non-null    float64
 9   Corruption Perception         158 non-null    float64
 10  Generosity                    158 non-null    float64
 11  Residual error                158 non-null    float64
 12  Happiness Score               158 non-null    float64
dtypes: float64(9), int64(2), object(2)
memory usage: 16.2+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Country                       157 non-null    object
 1   Region                        157 non-null    object
 2   Happiness Rank                157 non-null    int64
 3   year                          157 non-null    int64
 4   Lower Confidence Interval     157 non-null    float64
 5   Upper Confidence Interval     157 non-null    float64
 6   GDP per capita                157 non-null    float64
 7   Social support                157 non-null    float64
 8   Healthy Life Expectancy       157 non-null    float64
 9   Freedom to make life choices  157 non-null    float64
 10  Corruption Perception         157 non-null    float64
 11  Generosity                    157 non-null    float64
 12  Residual error                157 non-null    float64
 13  Happiness Score               157 non-null    float64
dtypes: float64(10), int64(2), object(2)
memory usage: 17.3+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Country                       155 non-null    object
 1   Happiness.Rank                155 non-null    int64
 2   year                          155 non-null    int64
 3   Whisker.high                  155 non-null    float64
 4   Whisker.low                   155 non-null    float64
 5   GDP per capita                155 non-null    float64
 6   Social support                155 non-null    float64
 7   Healthy Life Expectancy       155 non-null    float64
 8   Freedom to make life choices  155 non-null    float64
 9   Generosity                    155 non-null    float64
 10  Corruption Perception         155 non-null    float64
 11  Residual error                155 non-null    float64
 12  Happiness Score               155 non-null    float64
dtypes: float64(10), int64(2), object(1)
memory usage: 15.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Overall rank                  156 non-null    int64
 1   Country or region             156 non-null    object
 2   Residual error                0 non-null      float64
 3   GDP per capita                156 non-null    float64
 4   Social support                156 non-null    float64
 5   Healthy Life Expectancy       156 non-null    float64
 6   Freedom to make life choices  156 non-null    float64
 7   Generosity                    156 non-null    float64
 8   Corruption Perception         155 non-null    float64
 9   year                          156 non-null    int64
 10  Happiness Score               156 non-null    float64
dtypes: float64(8), int64(2), object(1)
memory usage: 13.5+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Overall rank                  156 non-null    int64
 1   Country or region             156 non-null    object
 2   Residual error                0 non-null      float64
 3   GDP per capita                156 non-null    float64
 4   Social support                156 non-null    float64
 5   Healthy Life Expectancy       156 non-null    float64
 6   Freedom to make life choices  156 non-null    float64
 7   Generosity                    156 non-null    float64
 8   Corruption Perception         156 non-null    float64
 9   year                          156 non-null    int64
 10  Happiness Score               156 non-null    float64
dtypes: float64(8), int64(2), object(1)
memory usage: 13.5+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Country name                    153 non-null    object
 1   Regional indicator              153 non-null    object
 2   year                            153 non-null    int64
 3   Standard error of ladder score  153 non-null    float64
 4   upperwhisker                    153 non-null    float64
 5   lowerwhisker                    153 non-null    float64
 6   Ladder score in Dystopia        153 non-null    float64
 7   GDP per capita                  153 non-null    float64
 8   Social support                  153 non-null    float64
 9   Healthy Life Expectancy         153 non-null    float64
 10  Freedom to make life choices    153 non-null    float64
 11  Generosity                      153 non-null    float64
 12  Corruption Perception           153 non-null    float64
 13  Residual error                  153 non-null    float64
 14  Happiness Score                 153 non-null    float64
dtypes: float64(12), int64(1), object(2)
memory usage: 18.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295 entries, 0 to 294
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      295 non-null    int64
 1   score   295 non-null    int64
dtypes: int64(2)
memory usage: 4.7 KB
None

In [265]:
# 필요한 데이터만 추출 ['GDP per capita', 'Healthy Life Expectancy', 'Social support', 'Freedom to make life choices', 'Generosity', 'Corruption Perception', 'Residual error']

train_col = ['GDP per capita', 'Social support', 'Healthy Life Expectancy', 'Freedom to make life choices', 'Generosity', 'Corruption Perception', 'Residual error', 'Happiness Score']
test_col = ['GDP per capita', 'Social support', 'Healthy Life Expectancy', 'Freedom to make life choices', 'Generosity', 'Corruption Perception', 'Residual error']

df['2015'] = df['2015'][train_col]
df['2016'] = df['2016'][train_col]
df['2017'] = df['2017'][train_col]
df['2018'] = df['2018'][train_col]
df['2019'] = df['2019'][train_col]
df['2020'] = df['2020'][train_col]

tf['2021'] = tf['2021'][test_col]
tf['2022'] = tf['2022'][test_col]

In [266]:
# 필요한 데이터 추출 및 병합과정(concat) -> index reset을 통해 오류가능성 제거
df['2018']['Residual error'] =  df['2018']['Happiness Score'] - (df['2018']['GDP per capita'] + df['2018']['Social support'] + df['2018']['Healthy Life Expectancy'] + df['2018']['Freedom to make life choices'] + df['2018']['Generosity'] + df['2018']['Corruption Perception'])
df['2019']['Residual error'] =  df['2019']['Happiness Score'] - (df['2019']['GDP per capita'] + df['2019']['Social support'] + df['2019']['Healthy Life Expectancy'] + df['2019']['Freedom to make life choices'] + df['2019']['Generosity'] + df['2019']['Corruption Perception'])


train_data = pd.concat([df['2015'],df['2016'],df['2017'],df['2018'],df['2019'],df['2020']],axis=0)
test_data = pd.concat([tf['2021'],tf['2022']],axis=0)

train_data = train_data.reset_index(drop=True)
test_data = test_data.reset_index(drop=True)

test_data

,GDP per capita,Social support,Healthy Life Expectancy,Freedom to make life choices,Generosity,Corruption Perception,Residual error
0,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,1.482,1.172,0.772,0.698,0.293,0.17,2.967
4,1.501,1.079,0.753,0.647,0.302,0.384,2.798
...,...,...,...,...,...,...,...
290,"1,503","0,815","0,280","0,571","0,012","0,102","0,187"
291,"0,785","0,133","0,462","0,621","0,187","0,544","0,536"
292,"0,947","0,690","0,270","0,329","0,106","0,105","0,548"
293,"1,392","0,498","0,631","0,103","0,082","0,034","0,216"
294,"0,758","0,000","0,289","0,000","0,089","0,005","1,263"

In [267]:
train_data.info()
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 935 entries, 0 to 934
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GDP per capita                935 non-null    float64
 1   Social support                935 non-null    float64
 2   Healthy Life Expectancy       935 non-null    float64
 3   Freedom to make life choices  935 non-null    float64
 4   Generosity                    935 non-null    float64
 5   Corruption Perception         934 non-null    float64
 6   Residual error                934 non-null    float64
 7   Happiness Score               935 non-null    float64
dtypes: float64(8)
memory usage: 58.6 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295 entries, 0 to 294
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GDP per capita                295 non-null    object
 1   Social support                295 non-null    object
 2   Healthy Life Expectancy       295 non-null    object
 3   Freedom to make life choices  295 non-null    object
 4   Generosity                    295 non-null    object
 5   Corruption Perception         295 non-null    object
 6   Residual error                295 non-null    object
dtypes: object(7)
memory usage: 16.3+ KB

In [268]:
# train 데이터는 float 형으로 제대로 들어가있는걸 확인했지만, 결측치가 존재할 수 있으니 최빈값 처리함 (pandas 함수의 fillna 활용)

for col in train_data.columns:
    if train_data[col].isnull().sum() != 0:
        train_data[col] = train_data[col].fillna(train_data[col].mode()[0])

In [269]:
# test data 확인결과 소숫점이 , 으로 표현된것을 확인 이를 소수로 수정함

for col in test_data.columns:
    for i in range(len(test_data[col])):
        if type(test_data[col][i]) != float:
            test_data[col][i] = test_data[col][i].replace(',','.')
            test_data[col][i] = float(test_data[col][i])
    test_data[col] = test_data[col].astype('float64')

print(test_data.info())

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295 entries, 0 to 294
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GDP per capita                295 non-null    float64
 1   Social support                295 non-null    float64
 2   Healthy Life Expectancy       295 non-null    float64
 3   Freedom to make life choices  295 non-null    float64
 4   Generosity                    295 non-null    float64
 5   Corruption Perception         295 non-null    float64
 6   Residual error                295 non-null    float64
dtypes: float64(7)
memory usage: 16.3 KB
None

In [270]:
print(train_data.info())
x_data = train_data.iloc[:,:-1].to_numpy()
y_data = train_data.iloc[:, -1].to_numpy()
test_data = test_data.to_numpy()

from sklearn.preprocessing import StandardScaler
std = StandardScaler()

x_data_std = std.fit_transform(x_data)
test_data_std = std.transform(test_data)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 935 entries, 0 to 934
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GDP per capita                935 non-null    float64
 1   Social support                935 non-null    float64
 2   Healthy Life Expectancy       935 non-null    float64
 3   Freedom to make life choices  935 non-null    float64
 4   Generosity                    935 non-null    float64
 5   Corruption Perception         935 non-null    float64
 6   Residual error                935 non-null    float64
 7   Happiness Score               935 non-null    float64
dtypes: float64(8)
memory usage: 58.6 KB
None

In [271]:
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor()
knn.fit(x_data_std, y_data)
pred = knn.predict(test_data_std)
pred

array([7.39794002, 7.4882    , 7.2164    , 7.05456002, 7.4474    ,
       7.3632    , 7.351     , 7.0498    , 7.351     , 6.9468    ,
       7.151     , 6.8526    , 6.9468    , 7.134     , 6.9414    ,
       6.50098001, 7.1888    , 6.54080003, 6.8666    , 6.52320001,
       6.44449997, 6.7346    , 6.93696002, 6.51180001, 6.59596002,
       6.3036    , 6.34148001, 6.4982    , 6.25171998, 6.0412    ,
       6.4254    , 6.50082   , 6.11004002, 6.28219996, 6.2982    ,
       6.453     , 6.19898001, 6.0122    , 6.0514    , 6.37189995,
       6.04474006, 5.79031997, 5.9834    , 6.18909997, 6.1918    ,
       6.21914003, 6.0712    , 5.9394    , 6.0412    , 5.97419997,
       5.816     , 6.1172    , 5.81719999, 5.8462    , 6.0192    ,
       6.10175993, 6.04474006, 5.66174003, 6.023     , 5.95973999,
       6.0412    , 5.9552    , 5.70740003, 5.7814    , 5.771     ,
       5.66590002, 5.94959996, 5.7802    , 6.0412    , 5.65619997,
       5.74459996, 5.6464    , 5.4264    , 5.80639999, 5.4426    ,
       5.78780003, 5.86697997, 4.89265997, 5.6289    , 5.4814    ,
       5.4462    , 5.53372004, 5.00738001, 5.23651996, 4.96846006,
       5.14491996, 5.22851992, 5.56379999, 5.31006005, 4.97907999,
       4.89606006, 5.14534001, 5.10716   , 5.4624    , 5.1438    ,
       4.94811997, 5.04820008, 4.49991997, 4.51520002, 4.94251993,
       4.92759996, 4.83031997, 4.52142   , 5.12679999, 4.6798    ,
       4.98936   , 4.84539997, 4.77811996, 4.9922    , 5.01396002,
       4.7876    , 4.579     , 4.97538001, 4.98368002, 4.82551996,
       4.87826004, 4.77926004, 4.77739998, 4.64643992, 4.67917992,
       4.41760001, 4.94736003, 4.56476   , 4.42379998, 4.62036003,
       4.8216    , 4.45911996, 4.24811997, 4.16005999, 4.14802002,
       3.90584001, 4.29799998, 4.16360001, 4.1226    , 4.10204001,
       4.31324001, 3.797     , 3.95880001, 3.86505999, 3.67266001,
       3.86599999, 3.89044004, 3.65815998, 3.6534    , 3.94315998,
       3.74098   , 3.40685999, 3.66619998, 3.04238   , 7.52136002,
       7.12251997, 6.74916003, 7.09290004, 7.14419999, 6.85190004,
       6.86419998, 6.6416    , 6.62389997, 6.7408    , 6.78450004,
       6.84579994, 6.68599998, 6.7172    , 6.96370002, 6.3364    ,
       6.78019994, 6.32342005, 6.35869997, 6.21779993, 6.47356002,
       6.19081998, 6.16351995, 6.4436    , 6.25151995, 6.16151995,
       6.41622   , 6.06754003, 6.20461996, 6.39709992, 6.214     ,
       6.12819997, 6.24561998, 6.19041998, 6.12801998, 6.50579996,
       6.19671995, 6.18909997, 6.1788    , 6.13441996, 5.9636    ,
       6.19041998, 5.97861998, 6.08321998, 6.25600001, 6.12821998,
       6.00081995, 6.13701998, 6.3558    , 6.17501998, 6.19041998,
       6.16351995, 6.35347999, 5.99876002, 6.05439997, 5.8726    ,
       6.19671995, 5.636     , 5.9986    , 5.99080001, 5.59366008,
       5.91673999, 5.91673999, 6.00885992, 5.89320001, 5.74801994,
       5.76219992, 5.70740004, 6.01681996, 6.20761998, 5.72299996,
       5.76999997, 5.88848003, 5.43359996, 5.83281998, 5.61101998,
       5.68821998, 5.59908008, 6.04610001, 5.71259995, 5.62087999,
       5.72471996, 5.67592004, 5.324     , 5.50480003, 5.67920004,
       5.09252004, 5.29007997, 5.29899997, 4.89614   , 4.61705999,
       5.82356002, 4.83360001, 4.88387994, 4.82711997, 5.16117999,
       5.10584002, 5.3306    , 4.77627997, 5.13576003, 4.736     ,
       4.95687997, 4.5788    , 4.804     , 4.82131991, 4.83599997,
       5.0878    , 4.55697999, 4.7446    , 4.71708009, 4.56960001,
       4.89116004, 4.4688    , 4.63348002, 4.3808    , 4.7446    ,
       4.37939995, 4.32559999, 4.69519999, 4.61103996, 4.2958    ,
       4.27188002, 4.2216    , 4.18300003, 4.24982008, 4.47300005,
       4.12958003, 4.3454    , 4.33215999, 3.9324    , 4.21507999,
       4.33942006, 4.2658    , 3.79766001, 4.2582    , 4.09185998,
       4.01345999, 3.57979998, 3.6475    , 3.75139999, 4.10735999,
       3.65938   , 3.40685999, 3.77664   , 4.1868    , 3.03270002])

In [272]:
submit['score'] = pred
submit.to_csv('submit', header=True, index=False)